[package]
name = "syncplay"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
md5 = { workspace = true }
serde = { workspace = true }
serde_json = "1.0.145"
thiserror = "2.0.16"
tokio-rustls = "0.26.3"
